name: mytechlab
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  percent_indicator: ^4.2.2
  intro_slider: ^3.0.9
  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.0.15
  firebase_auth: ^3.6.3
  firebase_core: ^1.20.1
  cloud_firestore: ^3.4.4
  modal_progress_hud: ^0.1.3
  email_validator: ^2.1.17
  file_picker: ^5.0.1
  firebase_storage: ^10.3.6
  url_launcher: ^6.1.5
  fluttertoast: ^8.0.9
  firebase_messaging: ^12.0.3
  image_picker: ^0.8.5+3
  flutter_local_notifications: ^9.8.0+1
  photo_view: ^0.14.0
  cupertino_icons: ^1.0.5
  cached_network_image: ^3.2.2
  image_cropper: ^3.0.0
  fluttericon: ^2.0.0
  curved_navigation_bar: ^1.0.3
  uuid: ^3.0.6
  animated_text_kit: ^4.2.2
  flutter_staggered_grid_view: ^0.6.2
  video_player: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    
  